import type { Finding, ReconPackage, ScanResult } from "../engine/types.ts";

export function money(dollars: number): string {
  const neg = dollars < 0;
  const v = Math.abs(dollars);
  return (neg ? "-$" : "$") + v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

/** Auto-compact for stat tiles: $4.2K / $1.3M, full below $10k. */
export function moneyCompact(dollars: number): string {
  const v = Math.abs(dollars);
  const sign = dollars < 0 ? "-" : "";
  if (v >= 1_000_000) return `${sign}$${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 10_000) return `${sign}$${(v / 1_000).toFixed(1)}K`;
  return sign + "$" + v.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

export function yearText(y: Finding["year"]): string {
  return Array.isArray(y) ? `${y[0]}→${y[1]}` : String(y);
}

export const SEVERITY_LABEL = { high: "High", review: "Review", info: "Info" } as const;
export const SEVERITY_ICON = { high: "▲", review: "●", info: "○" } as const;

/** Plain-text rendering of a finding, ready for a finding letter. */
export function findingToText(f: Finding, pkg: ReconPackage): string {
  const lines: string[] = [];
  lines.push(`${f.check_id} · ${SEVERITY_LABEL[f.severity]} · ${yearText(f.year)}${f.category ? ` · ${f.category}` : ""}`);
  lines.push(f.title);
  lines.push("");
  lines.push(f.narrative);
  lines.push("");
  if (f.tenant_impact_usd !== undefined) lines.push(`Estimated tenant impact: ${money(f.tenant_impact_usd)}`);
  if (f.tenant_exposure_usd !== undefined) lines.push(`Tenant-level amount at stake: ${money(f.tenant_exposure_usd)}`);
  lines.push("Working:");
  const w = Math.min(40, Math.max(...f.working.map((r) => r.label.length)));
  for (const row of f.working) lines.push(`  ${row.label.padEnd(w)}  ${row.value}`);
  lines.push("");
  lines.push(`Source: ${f.refs.join("; ")}`);
  lines.push(`Package: ${pkg.meta.package_id} — ${pkg.meta.tenant_name}, ${pkg.meta.property_name}. Generated by the Recon Red-Flag Scanner (deterministic engine; no AI in the arithmetic).`);
  return lines.join("\n");
}

export function resultToText(r: ScanResult, pkg: ReconPackage): string {
  const head = [
    `Recon Red-Flag Scanner — ${pkg.meta.package_id} (${pkg.meta.tenant_name}, ${pkg.meta.property_name})`,
    `${r.totals.high} high · ${r.totals.review} review · ${r.totals.info} info · estimated tenant impact ${money(r.totals.estimated_impact_usd)}`,
    `Checks run: ${r.checks_run.join(", ")}${r.skipped.length ? `; not run: ${r.skipped.map((s) => `${s.check_id} (${s.reason})`).join("; ")}` : ""}`,
    "",
  ];
  return head.concat(r.findings.map((f) => findingToText(f, pkg) + "\n\n" + "—".repeat(40) + "\n")).join("\n");
}
